"""test_sample_batch_fixture.py — regression coverage for
data/samples/sample_batch_claims.csv (generated by
app/ml/generate_sample_batch.py, for manually exercising POST
/score/batch and the dashboard's Batch review page). This file locks in
that the fixture always actually works against the real API: every row
scores successfully, the deliberately blank optional fields round-trip
as null (not a crash — PB-20/PB-26) via GET /claims/{id} afterward, and
the "high-risk-pattern" rows score meaningfully higher on average than
the "low-risk-pattern" rows, so the fixture stays a genuinely useful
manual-testing aid and not just 60 rows of noise."""
import csv
import statistics
import sys
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

FIXTURE_PATH = Path(__file__).resolve().parents[2] / "data" / "samples" / "sample_batch_claims.csv"

TEST_API_KEY = "test-suite-api-key"


@pytest.fixture()
def client(tmp_path, monkeypatch):
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{tmp_path}/test.db")
    monkeypatch.setenv("AEGIS_API_KEY", TEST_API_KEY)
    for mod in list(sys.modules):
        if mod.startswith("app."):
            del sys.modules[mod]
    from app.main import app
    with TestClient(app, headers={"X-API-Key": TEST_API_KEY}) as c:
        yield c


def test_fixture_file_exists():
    assert FIXTURE_PATH.exists(), "run `python -m app.ml.generate_sample_batch` from backend/ to (re)create it"


def test_every_row_scores_successfully(client):
    with open(FIXTURE_PATH, "rb") as f:
        r = client.post("/score/batch", files={"file": ("sample_batch_claims.csv", f, "text/csv")})
    assert r.status_code == 200
    rows = r.json()
    with open(FIXTURE_PATH) as f:
        n_input_rows = sum(1 for _ in csv.DictReader(f))
    assert len(rows) == n_input_rows
    for row in rows:
        assert 0.0 <= row["fraud_probability"] <= 1.0
        assert row["risk_grade"] in {"Low", "Medium", "High"}
        assert row["top_reasons"]


def test_rows_with_blank_optional_fields_are_retrievable_afterward(client):
    """The fixture deliberately includes a few rows with a blank optional
    field (see generate_sample_batch.py) — this is the exact PB-26
    regression shape: must not 500 on GET after a successful score."""
    with open(FIXTURE_PATH, "rb") as f:
        r = client.post("/score/batch", files={"file": ("sample_batch_claims.csv", f, "text/csv")})
    assert r.status_code == 200
    claim_ids = [row["claim_id"] for row in r.json()]
    for claim_id in claim_ids:
        detail = client.get(f"/claims/{claim_id}")
        assert detail.status_code == 200
    listing = client.get("/claims")
    assert listing.status_code == 200
    assert len(listing.json()) == len(claim_ids)


def test_high_risk_pattern_rows_score_meaningfully_higher_than_low_risk_pattern_rows(client):
    """Sanity check that the fixture's engineered scenarios actually mean
    something to the shipped model, not just that the API accepts them —
    a crude proxy on the raw CSV (major/total-loss damage + no witnesses
    + no police report, vs. trivial/minor damage + a police report)
    should separate cleanly in the scored fraud_probability."""
    with open(FIXTURE_PATH) as f:
        raw_rows = list(csv.DictReader(f))
    with open(FIXTURE_PATH, "rb") as f:
        r = client.post("/score/batch", files={"file": ("sample_batch_claims.csv", f, "text/csv")})
    assert r.status_code == 200
    scored_rows = r.json()

    high_like, low_like = [], []
    for raw, scored in zip(raw_rows, scored_rows):
        if raw["incident_severity"] in ("Major Damage", "Total Loss") and raw["witnesses"] == "0" and raw["police_report_available"] == "NO":
            high_like.append(scored["fraud_probability"])
        elif raw["incident_severity"] in ("Trivial Damage", "Minor Damage") and raw["police_report_available"] == "YES":
            low_like.append(scored["fraud_probability"])

    assert high_like and low_like, "sanity check: the fixture should contain both scenario shapes"
    assert statistics.mean(high_like) > statistics.mean(low_like)
