"""test_realistic_batch_fixture.py — regression coverage for the 10,000-row
research-grounded dataset (data/samples/realistic_claims_10k_part{1,2}.csv
+ realistic_claims_10k_full.csv, generated by
app/ml/generate_realistic_batch.py).

Scoring all 10,000 rows through TestClient on every test run would make
the suite slow (SHAP explanation cost per row) for marginal extra
confidence beyond what a live smoke test already established (see this
fixture's delivery message: both 5,000-row parts scored 200 end-to-end,
10,000 claims round-tripped through GET /claims/{id} including several
with blank optional fields, and the intended high/ambiguous/low pattern
ordering held: mean fraud_probability 0.415 > 0.358 > 0.286). So these
tests check the things a full live run can't (that the two parts are
correctly split, that the file the maintainer runs by hand stays
upload-able) plus a representative SAMPLE of live scoring — not a
full 10,000-row score on every `pytest` run.
"""
import csv
import statistics
import sys
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core import config

SAMPLES_DIR = Path(__file__).resolve().parents[2] / "data" / "samples"
PART1_PATH = SAMPLES_DIR / "realistic_claims_10k_part1.csv"
PART2_PATH = SAMPLES_DIR / "realistic_claims_10k_part2.csv"
FULL_PATH = SAMPLES_DIR / "realistic_claims_10k_full.csv"

TEST_API_KEY = "test-suite-api-key"
SAMPLE_SIZE = 300  # rows scored per test run, from the front of each part — enough to catch a systemic error, fast enough for the suite


@pytest.fixture()
def client(tmp_path, monkeypatch):
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{tmp_path}/test.db")
    monkeypatch.setenv("AEGIS_API_KEY", TEST_API_KEY)
    for mod in list(sys.modules):
        if mod.startswith("app."):
            del sys.modules[mod]
    from app.main import app
    with TestClient(app, headers={"X-API-Key": TEST_API_KEY}) as c:
        yield c


def _read_rows(path, limit=None):
    with open(path) as f:
        reader = csv.DictReader(f)
        rows = list(reader)
    return rows[:limit] if limit else rows


def _post_sample(client, path, n=SAMPLE_SIZE):
    """Uploads only the first n rows of a fixture part as their own
    in-memory CSV, so a test run doesn't have to score all 5,000."""
    import io
    rows = _read_rows(path, limit=n)
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    csv_bytes = io.BytesIO(buf.getvalue().encode())
    return rows, client.post("/score/batch", files={"file": ("sample.csv", csv_bytes, "text/csv")})


def test_fixture_files_exist():
    for path in (PART1_PATH, PART2_PATH, FULL_PATH):
        assert path.exists(), "run `python -m app.ml.generate_realistic_batch` from backend/ to (re)create it"


def test_parts_are_each_within_max_batch_rows_and_together_make_the_full_file():
    """The whole reason this dataset ships as two files: MAX_BATCH_ROWS
    (app/core/config.py) rejects a single request over that many rows —
    a raw 10,000-row upload would 413. Each part must clear the cap on
    its own, and the two parts must be a lossless split of the full
    10,000-row file (same rows, none dropped or duplicated)."""
    part1 = _read_rows(PART1_PATH)
    part2 = _read_rows(PART2_PATH)
    full = _read_rows(FULL_PATH)

    assert len(part1) <= config.MAX_BATCH_ROWS
    assert len(part2) <= config.MAX_BATCH_ROWS
    assert len(part1) + len(part2) == len(full) == 10_000


def test_full_10k_file_is_rejected_by_score_batch_but_each_part_is_accepted(client):
    """Documents, as a live assertion rather than just a comment, exactly
    why the dataset is delivered pre-split: uploading the combined file
    in one request 413s; each part alone does not."""
    import io
    with open(FULL_PATH, "rb") as f:
        full_bytes = f.read()
    r = client.post("/score/batch", files={"file": ("full.csv", io.BytesIO(full_bytes), "text/csv")})
    assert r.status_code == 413

    for path in (PART1_PATH, PART2_PATH):
        rows, r = _post_sample(client, path, n=50)
        assert r.status_code == 200
        assert len(r.json()) == 50


def test_sample_of_each_part_scores_successfully(client):
    for path in (PART1_PATH, PART2_PATH):
        rows, r = _post_sample(client, path)
        assert r.status_code == 200
        scored = r.json()
        assert len(scored) == len(rows)
        for row in scored:
            assert 0.0 <= row["fraud_probability"] <= 1.0
            assert row["risk_grade"] in {"Low", "Medium", "High"}
            assert row["top_reasons"]


def test_blank_optional_fields_in_sample_are_retrievable_afterward(client):
    """PB-26 regression shape at this dataset's scale: a batch-scored
    claim with a blank optional CSV cell must not 500 on retrieval."""
    rows, r = _post_sample(client, PART1_PATH)
    assert r.status_code == 200
    claim_ids = [row["claim_id"] for row in r.json()]

    had_blank = False
    for raw, claim_id in zip(rows, claim_ids):
        if any(v == "" for v in raw.values()):
            had_blank = True
            detail = client.get(f"/claims/{claim_id}")
            assert detail.status_code == 200
    assert had_blank, "sanity check: the sampled rows should include at least one with a blank optional field"

    # GET /claims defaults to limit=200 (app/api/claims.py) — pass an
    # explicit limit wide enough for this sample's claim_ids, rather than
    # assuming the default returns everything ever scored.
    listing = client.get("/claims", params={"limit": len(claim_ids)})
    assert listing.status_code == 200
    assert len(listing.json()) == len(claim_ids)


def test_high_risk_pattern_rows_score_meaningfully_higher_than_low_risk_pattern_rows(client):
    """Same red-flag proxy as test_sample_batch_fixture.py's equivalent
    test, applied to this fixture's larger, noisier, probabilistic
    pattern generation (see generate_realistic_batch.py's docstring) —
    confirms the research-grounded red flags (no witnesses, no police
    report, major/total-loss severity) still separate cleanly on average
    even though no single row is a guaranteed high- or low-risk case."""
    rows, r = _post_sample(client, PART1_PATH, n=1000)
    assert r.status_code == 200
    scored = r.json()

    high_like, low_like = [], []
    for raw, result in zip(rows, scored):
        if raw["incident_severity"] in ("Major Damage", "Total Loss") and raw["witnesses"] == "0" and raw["police_report_available"] == "NO":
            high_like.append(result["fraud_probability"])
        elif raw["incident_severity"] in ("Trivial Damage", "Minor Damage") and raw["police_report_available"] == "YES":
            low_like.append(result["fraud_probability"])

    assert high_like and low_like, "sanity check: a 1000-row sample should contain both proxy shapes"
    assert statistics.mean(high_like) > statistics.mean(low_like)
