"""
generate_metrics_report.py — PB-15: this project's working rules require
every performance number quoted in `docs/` to come from `models/metrics.json`
(and the other real `data/processed/*.csv` artifacts train.py/evaluate_oracle.py
produce), never be hand-typed. In practice, before this ticket, that meant an
AI or human manually re-reading `metrics.json` before writing a number into
`REBUILD_NOTES.md`/`README.md` prose — a real, reproduced instance of exactly
the failure this rule exists to prevent was found while building this
ticket: `docs/REBUILD_NOTES.md`'s comparison table quoted "Oracle ROC-AUC
~0.48 (random)", written against an earlier training run; the CURRENT
`models/metrics.json` (after later tickets retrained the model, e.g. PB-24's
encoding fix) reports Oracle ROC-AUC 0.463 with a bootstrap 95% CI of
[0.443, 0.481] — a CI that no longer even contains 0.5, so "random" is no
longer the most accurate one-word characterization; see §27's note in
REBUILD_NOTES.md for the fix.

Run: python -m app.ml.generate_metrics_report   (from backend/)
Writes docs/CURRENT_METRICS.md (always regenerated from the artifacts
currently on disk — safe to re-run after any retrain) and also prints it,
so a reviewer or thesis writer can quote numbers straight from its stdout
without opening any file at all.
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[3]
MODELS_DIR = PROJECT_ROOT / "models"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
ORACLE_DIR = PROJECT_ROOT / "data" / "external" / "oracle"
DOCS_DIR = PROJECT_ROOT / "docs"


def _pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def _f3(x: float) -> str:
    return f"{x:.3f}"


def load_metrics() -> dict:
    with open(MODELS_DIR / "metrics.json") as f:
        return json.load(f)


def load_oracle_report() -> dict | None:
    path = ORACLE_DIR / "oracle_validation_report.json"
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)


def load_champion_decision() -> dict | None:
    path = PROCESSED_DIR / "champion_decision.json"
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)


def build_report_markdown() -> str:
    metrics = load_metrics()
    oracle = load_oracle_report()
    champion = load_champion_decision()
    cv_df = pd.read_csv(PROCESSED_DIR / "cross_validation_results.csv") if (PROCESSED_DIR / "cross_validation_results.csv").exists() else None

    primary = metrics["primary_model"]
    primary_row = next(r for r in metrics["model_comparison"] if r["model"] == primary)

    lines: list[str] = []
    lines.append("# Current metrics (auto-generated — do not hand-edit)")
    lines.append("")
    lines.append(f"Generated by `python -m app.ml.generate_metrics_report` directly from "
                  f"`models/metrics.json` and the `data/processed/`/`data/external/oracle/` "
                  f"artifacts on disk at generation time. Re-run after any retrain; never "
                  f"hand-edit a number in this file — edit the pipeline and regenerate instead.")
    lines.append("")
    lines.append(f"**Champion model:** `{primary}` &nbsp;·&nbsp; "
                  f"**Operating threshold:** {primary_row['threshold']} &nbsp;·&nbsp; "
                  f"**n_train:** {metrics['n_train']} &nbsp;·&nbsp; "
                  f"**n_test:** {metrics['n_test']} &nbsp;·&nbsp; "
                  f"**n_features:** {metrics['n_features']} &nbsp;·&nbsp; "
                  f"**train fraud rate:** {_pct(metrics['fraud_rate'])}")
    lines.append("")

    lines.append("## Held-out single-split comparison")
    lines.append("")
    lines.append("| Model | Threshold | Recall | Precision | F1 | PR-AUC | ROC-AUC | Accuracy |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for row in metrics["model_comparison"]:
        marker = " **(shipped)**" if row["model"] == primary else ""
        lines.append(
            f"| {row['model']}{marker} | {row['threshold']} | {_pct(row['recall'])} | "
            f"{_pct(row['precision'])} | {_f3(row['f1'])} | {_f3(row['pr_auc'])} | "
            f"{_f3(row['roc_auc'])} | {_pct(row['accuracy'])} |"
        )
    lines.append("")

    if cv_df is not None:
        lines.append("## 5-fold cross-validation (full pipeline refit per fold, mean ± SD)")
        lines.append("")
        lines.append("| Model | ROC-AUC | PR-AUC | F1 | Recall | Precision |")
        lines.append("|---|---|---|---|---|---|")
        for _, r in cv_df.iterrows():
            lines.append(
                f"| {r['model']} | {_f3(r['roc_auc_mean'])} ± {_f3(r['roc_auc_std'])} | "
                f"{_f3(r['pr_auc_mean'])} ± {_f3(r['pr_auc_std'])} | "
                f"{_f3(r['f1_mean'])} ± {_f3(r['f1_std'])} | "
                f"{_f3(r['recall_mean'])} ± {_f3(r['recall_std'])} | "
                f"{_f3(r['precision_mean'])} ± {_f3(r['precision_std'])} |"
            )
        lines.append("")

    if champion is not None:
        lines.append("## Champion selection (D4 — measured, not defaulted)")
        lines.append("")
        lines.append(f"- D4 default absent evidence: `{champion['default_champion_per_D4']}`")
        lines.append(f"- Measured champion (this project's own metric hierarchy, paired 5-fold CV): `{champion['measured_champion']}`")
        tt = champion.get("paired_ttest", {})
        if "recall" in tt and "f1" in tt:
            lines.append(
                f"- Paired t-test (n_folds={tt.get('n_folds', '?')}): recall p={tt['recall']['p']:.4f}, "
                f"F1 p={tt['f1']['p']:.4f} — **low statistical power by construction** "
                f"(only {tt.get('n_folds', 5) - 1} degrees of freedom on a 5-fold paired test); "
                f"treated as real, reproducible, directionally-consistent evidence for THIS "
                f"dataset, not as license to over-claim certainty beyond it."
            )
        lines.append("")

    if oracle is not None:
        lines.append("## Oracle external validation")
        lines.append("")
        ih = oracle["internal_holdout_metrics"]
        om = oracle["oracle_metrics"]
        lines.append(f"| | Internal holdout | Oracle (external) |")
        lines.append(f"|---|---|---|")
        lines.append(f"| ROC-AUC | {_f3(ih['roc_auc'])} | {_f3(om['roc_auc'])} |")
        lines.append(f"| PR-AUC | {_f3(ih['pr_auc'])} | {_f3(om['pr_auc'])} |")
        cm = om["confusion_matrix"]
        lines.append(f"| Confusion matrix @ operating threshold ({om['operating_threshold']}) | — | "
                      f"TN {cm['tn']} / FP {cm['fp']} / FN {cm['fn']} / TP {cm['tp']} |")
        lines.append("")
        if "oracle_metrics_ci" in oracle:
            ci = oracle["oracle_metrics_ci"]
            roc_ci = ci.get("roc_auc", {})
            if roc_ci:
                contains_half = roc_ci["ci_lower"] <= 0.5 <= roc_ci["ci_upper"]
                verdict = (
                    "consistent with random ranking (CI contains 0.5)"
                    if contains_half else
                    "statistically distinguishable from random — the CI does NOT contain 0.5, "
                    "so this is measurably below chance, not merely indistinguishable from it"
                )
                lines.append(
                    f"Oracle ROC-AUC bootstrap 95% CI: [{_f3(roc_ci['ci_lower'])}, "
                    f"{_f3(roc_ci['ci_upper'])}] (n_boot={roc_ci.get('n_boot_effective', '?')}) — {verdict}."
                )
                lines.append("")
        lines.append(
            "**Statistical caveat (SH-05):** Oracle's 15,420 rows give this comparison high "
            "statistical power for what it measures — but PR-AUC's own baseline shifts with "
            "class prevalence (this project's internal fraud rate is "
            f"{_pct(metrics['fraud_rate'])}; Oracle's is far lower), so the internal-vs-Oracle "
            "PR-AUC gap above is not read the same way ROC-AUC's fixed 0.5 random baseline is — "
            "part of the gap reflects prevalence, not model degradation alone. The primary, "
            "prevalence-independent evidence for the generalization failure is the SHAP-weight "
            "constant-feature analysis in docs/REBUILD_NOTES.md (Oracle has no equivalent field "
            "for most of the model's top-weighted features), not the PR-AUC number alone."
        )
        lines.append("")

    return "\n".join(lines) + "\n"


def main():
    report = build_report_markdown()
    out_path = DOCS_DIR / "CURRENT_METRICS.md"
    out_path.write_text(report)
    print(report)
    print(f"[written to {out_path}]")


if __name__ == "__main__":
    main()
