"""
generate_metrics_report.py — writes docs/CURRENT_METRICS.md ENTIRELY from
artifacts (models/metrics.json, models/risk_policy.json, data/processed/*,
data/external/oracle/*). Never hand-edit the output; re-run after training.

Run: python -m app.ml.generate_metrics_report   (from backend/)
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from app.ml.reporting import calibration_sentence, champion_vs_rule_sentence, roc_ci_verdict

PROJECT_ROOT = Path(__file__).resolve().parents[3]
MODELS_DIR = PROJECT_ROOT / "models"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
ORACLE_DIR = PROJECT_ROOT / "data" / "external" / "oracle"
DOCS_DIR = PROJECT_ROOT / "docs"


def _pct(x): return f"{x * 100:.1f}%"
def _f3(x): return f"{x:.3f}"


def _json(path):
    return json.load(open(path)) if Path(path).exists() else None


def load_metrics() -> dict:
    return _json(MODELS_DIR / "metrics.json")


def load_oracle_report():
    return _json(ORACLE_DIR / "oracle_validation_report.json")


def load_champion_decision():
    return _json(PROCESSED_DIR / "champion_decision.json")


def _table(df: pd.DataFrame, fmt: dict | None = None) -> list[str]:
    fmt = fmt or {}
    cols = list(df.columns)
    out = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        out.append("| " + " | ".join(fmt.get(c, lambda v: f"{v:.3f}" if isinstance(v, float) else str(v))(r[c]) for c in cols) + " |")
    return out


def build_report_markdown() -> str:
    m, dec, orc = load_metrics(), load_champion_decision(), load_oracle_report()
    policy = _json(MODELS_DIR / "risk_policy.json")
    champ = m["primary_model"]
    L = ["# Current metrics (auto-generated — do not hand-edit)", "",
         "Generated by `python -m app.ml.generate_metrics_report` from the artifacts on disk. "
         "Every number, the champion's name and every p-value below are read from files written by the "
         "pipeline (`python -m app.ml.run_all`); none is typed.", "",
         f"**Champion:** `{champ}` · **calibration:** {m['calibration']['chosen']} · "
         f"**development rows:** {m['n_train']} · **test rows:** {m['n_test']} · **features:** {m['n_features']} · "
         f"**development fraud rate:** {_pct(m['fraud_rate'])}", ""]

    # --- selection
    if dec:
        L += ["## 1. Model selection (development rows only)", ""]
        L += [f"- **{k.replace('_', ' ')}:** {v}" for k, v in dec["protocol"].items()]
        L += ["", "**Decision trail (applied mechanically):**", ""]
        L += [f"{i}. `{t['candidate']}` — {t['decision']}" + (f" (p = {t['vs_best_p']:.3f})" if "vs_best_p" in t else "")
              for i, t in enumerate(dec["decision_trail"], 1)]
        L += ["", f"**Against the rule baseline:** {champion_vs_rule_sentence(dec)}", ""]
        sm = pd.read_csv(PROCESSED_DIR / "model_selection_summary.csv").sort_values("pr_auc_mean", ascending=False)
        sm = sm[["model", "pr_auc_mean", "pr_auc_std", "roc_auc_mean", "f1_mean", "recall_mean", "precision_mean", "threshold_mean"]]
        L += _table(sm) + [""]
        pt = pd.read_csv(PROCESSED_DIR / "pairwise_tests.csv")
        L += ["Pairwise corrected resampled t-tests (a minus b):", ""]
        L += _table(pt[["a", "b", "metric", "mean_difference", "a_wins_folds", "n_folds", "p_corrected", "significant"]],
                    {"a_wins_folds": str, "n_folds": str, "significant": lambda v: "yes" if v else "no"}) + [""]

    smote = PROCESSED_DIR / "smote_vs_classweight_comparison.csv"
    if smote.exists():
        L += ["## 2. Imbalance strategy (development rows only)", "",
              "Paired 5-fold CV at threshold 0.5. Class weighting alone is the shipped approach (SMOTE removed).", ""]
        L += _table(pd.read_csv(smote)[["variant", "pr_auc_mean", "roc_auc_mean", "recall_mean", "f1_mean"]]) + [""]

    ab = pd.read_csv(PROCESSED_DIR / "proxy_feature_ablation.csv")
    L += ["## 3. Proxy-feature ablation (development rows only, champion family, 5x2 CV)", ""]
    L += _table(ab) + ["", "Hobby/occupation proxy features stay OFF in the shipped model by governance decision, "
                       "even though the table shows they raise PR-AUC on this dataset.", ""]

    L += ["## 4. Calibration", "", calibration_sentence(m["calibration"]), "",
          f"> Rule amendment (disclosed): {m['calibration'].get('amendment', '—')}", ""]
    cs = pd.read_csv(PROCESSED_DIR / "calibration_summary.csv")
    L += _table(cs) + ["", "Reliability plot: `data/processed/reliability_plot.png` (bins in `reliability_curves.csv`). "
                       "The champion's rows are the calibrated model; other rows are raw.", ""]

    L += ["## 5. The three thresholds (kept separate)", "",
          f"1. **Display bands:** Low < {policy['medium_edge']:.3f} ≤ Medium < {policy['high_edge']:.3f} ≤ High. "
          f"Rule: {policy['rule']['description']}"]
    for band, p in policy["development_band_profile"].items():
        L.append(f"    - {band}: {_pct(p['share_of_claims'])} of development claims, {_pct(p['share_of_fraud'])} of fraud")
    L.append(f"2. **Operational review threshold:** {m['operating_threshold']:.2f} (F1-optimal on development out-of-fold scores).")
    cost = pd.read_csv(PROCESSED_DIR / "cost_sensitivity.csv")
    flag_all = int((cost["flag_rate"] >= 0.99).sum())
    L += [f"3. **Cost-sensitivity thresholds (not used for decisions):** across {len(cost)} assumption sets, the "
          f"cost-minimising threshold ranges {cost['threshold'].min():.2f}–{cost['threshold'].max():.2f}; in {flag_all} "
          f"of {len(cost)} sets the cost-minimising policy is to review (nearly) every claim.", ""]
    L += _table(cost[["review_cost", "fraud_share", "recovery_rate", "threshold", "recall", "precision", "flag_rate"]]) + [""]

    L += ["## 6. Test set (200 rows, used once)", ""]
    mc = pd.DataFrame(m["model_comparison"])
    L += _table(mc[["model", "threshold", "recall", "precision", "f1", "pr_auc", "roc_auc", "test_brier", "test_ece"]]) + [""]
    ba = m["baseline_agreement"]
    L += [f"Champion vs rule on test: identical review decision on {_pct(ba['test_decision_agreement'])} of "
          f"{ba['n_test']} claims ({ba['flagged_by_champion_not_rule']} flagged only by the champion, "
          f"{ba['flagged_by_rule_not_champion']} only by the rule).", ""]
    ci = pd.read_csv(PROCESSED_DIR / "holdout_bootstrap_ci.csv")
    L += ["Bootstrap 95% CIs on the test set:", ""]
    L += _table(ci[ci["metric"].isin(["roc_auc", "pr_auc", "recall", "f1"])][["model", "metric", "point_estimate", "ci_lower", "ci_upper"]]) + [""]

    fi = pd.read_csv(PROCESSED_DIR / "shap_importance_by_field.csv").head(10)
    L += ["## 7. Global SHAP importance, grouped to parent fields (top 10)", ""]
    L += _table(fi[["display_name", "share_of_total"]], {"share_of_total": _pct}) + [""]

    if orc:
        short, long = roc_ci_verdict(orc["oracle_metrics"]["roc_auc"], orc.get("oracle_metrics_ci", {}).get("roc_auc"))
        L += ["## 8. Oracle external validation", "", f"**Verdict: {short}.** {long}.", "",
              f"Model evaluated: `{orc['model']}`. Field mapping: {orc['field_mapping_counts']} "
              f"(table: `data/external/oracle/oracle_field_mapping.csv`). Features still variable after mapping: "
              f"{orc['n_features_variable_on_oracle']} of {orc['n_features_total']}; SHAP weight on constant features: "
              f"{_pct(orc['share_of_shap_weight_constant_on_oracle'])}.", ""]
        L += _table(pd.DataFrame([{"": "internal test", "roc_auc": orc["internal_holdout_metrics"]["roc_auc"], "pr_auc": orc["internal_holdout_metrics"]["pr_auc"]},
                                  {"": "Oracle", "roc_auc": orc["oracle_metrics"]["roc_auc"], "pr_auc": orc["oracle_metrics"]["pr_auc"]}])) + [""]
        ua = ORACLE_DIR / "oracle_univariate_auc.csv"
        if ua.exists():
            L += ["Univariate AUC of every feature that still varies on Oracle (development vs Oracle):", ""]
            L += _table(pd.read_csv(ua), {"direction_reverses": lambda v: "yes" if v else "no"}) + [""]
        sm2 = PROCESSED_DIR / "oracle_model_comparison.csv"
        if sm2.exists():
            L += ["Stress test — a DIFFERENT question (fresh models trained on Oracle's own fields):", ""]
            L += _table(pd.read_csv(sm2)) + [""]

    pr = PROCESSED_DIR / "sensitivity_probe.csv"
    if pr.exists():
        L += ["## 9. Sensitivity probe (reference claim, one field varied at a time)", ""]
        L += _table(pd.read_csv(pr)[["field", "value", "fraud_risk_score", "risk_band", "flagged_for_review"]]) + [""]
    return "\n".join(L) + "\n"


def main():
    report = build_report_markdown()
    out = DOCS_DIR / "CURRENT_METRICS.md"
    out.write_text(report)
    print(report)
    print(f"[written to {out}]")


if __name__ == "__main__":
    main()
