"""
main.py — Aegis Risk Engine FastAPI app.

Run (dev):  uvicorn app.main:app --reload --port 8000   (from backend/)
Docs:       http://localhost:8000/docs (auto-generated by FastAPI)
"""
from __future__ import annotations

from contextlib import asynccontextmanager

from fastapi import FastAPI

from app.api import audit, claims, feedback, ingestion, monitoring, scoring
from app.db.models import AuditLogEntry
from app.db.session import SessionLocal, init_db
from app.ml.inference import FraudScoringService


@asynccontextmanager
async def lifespan(_app: FastAPI):
    init_db()
    service = FraudScoringService.instance()  # load model artifacts once, fail fast if missing

    # PB-17: model_reloaded was a documented AuditLogEntry.event_type that
    # nothing ever emitted. Process startup — the one place a model
    # actually gets (re)loaded into memory — is the correct place to emit
    # it, so the audit timeline has a real record of which model version
    # was live from what time.
    db = SessionLocal()
    try:
        db.add(AuditLogEntry(
            event_type="model_reloaded",
            detail={"model_version": service.model_version, "operating_threshold": service.operating_threshold},
        ))
        db.commit()
    finally:
        db.close()

    yield


app = FastAPI(
    title="Aegis Risk Engine",
    description="Explainable insurance-claim fraud scoring — DCIT400 FYP.",
    version="1.0.0",
    lifespan=lifespan,
)


@app.get("/health")
def health():
    service = FraudScoringService.instance()
    return {"status": "ok", "model_version": service.model_version, "operating_threshold": service.operating_threshold}


app.include_router(scoring.router)
app.include_router(claims.router)
app.include_router(feedback.router)
app.include_router(audit.router)
app.include_router(monitoring.router)
app.include_router(ingestion.router)
